[package]
name = "aptos-counter"
version = "1.0.0"
authors = []

[addresses]
publisher = "1288520aac29b6fdb911aebd0d21e76a8ae9e4b6ae81bbb305d9ae384e74da26"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
